#!/bin/bash

#--------------------start-block replace the original XYZ coordinates of input by the 6th vibrational image from v006.xyz file ---------------------------

input_name=$(echo "$1" | awk -F '[.]' '{print $1}')

sed -n '1,/*/p' "$input_name".inp > "$input_name"-tmp.inp	#coping the command block of ORCA input

mv "$input_name"-tmp.inp "$input_name".inp

xyz_name=$(ls "$input_name".*.v006.xyz)

num_of_atoms=$(head -1 "$xyz_name")

num_of_atoms=$((num_of_atoms+2))

crop_start=$((num_of_atoms*5+3))
crop_end=$((num_of_atoms*6))

sed -n "$crop_start,$crop_end p" "$xyz_name" | awk '{printf "%s %15s %15s %15s\n" ,$1, $2, $3, $4}' >> "$input_name".inp 			#coping the xyz coordinates of 6th to new input 

echo "*" >> "$input_name".inp 

exit 0
#--------------------end-block replace the original XYZ coordinates of input by the 6th vibrational image from v006.xyz file ---------------------------